#!/bin/bash
# Generates the per-tool bindings from the portable sources, so procedures are
# written once and every tool reads its own dialect:
#
#   agents/skills/<name>.md     -> .claude/skills/<name>/SKILL.md   (Claude Code skill)
#                               -> .agents/workflows/<name>.md      (Antigravity /name workflow)
#   agents/reviewers/<name>.md  -> .claude/agents/<name>.md         (Claude Code subagent)
#
# The generated directories are fully owned by this script: edit the sources,
# re-run it, commit both. Tools that read AGENTS.md natively (Cursor, Codex,
# Zed, Copilot, Gemini CLI) need no binding. Sources must start with YAML
# frontmatter (--- ... ---); a GENERATED marker is inserted right after it.
#
#   usage: scripts/sync-adapters.sh            regenerate the bindings
#          scripts/sync-adapters.sh --check    verify bindings match the sources
#                                              (exit 1 on drift; used in CI)
set -euo pipefail
cd "$(dirname "$0")/.."

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

FAIL=0
EXPECTED=()

render() {
  awk -v src="$1" '
    { print }
    NR > 1 && $0 == "---" && !done {
      print ""
      print "<!-- GENERATED from " src " by scripts/sync-adapters.sh — edit the source and re-run; do not edit this file. -->"
      done = 1
    }
  ' "$1"
}

put() {
  local src="$1" dest="$2" tmp
  EXPECTED+=("$dest")
  tmp="$(mktemp)"
  render "$src" > "$tmp"
  if [ "$CHECK" -eq 1 ]; then
    cmp -s "$tmp" "$dest" || { echo "drift: $dest is out of sync with $src — run scripts/sync-adapters.sh" >&2; FAIL=1; }
    rm -f "$tmp"
  else
    mkdir -p "$(dirname "$dest")"
    mv "$tmp" "$dest"
    chmod 644 "$dest"
  fi
}

for src in agents/skills/*.md; do
  name="$(basename "$src" .md)"
  put "$src" ".claude/skills/$name/SKILL.md"
  put "$src" ".agents/workflows/$name.md"
done

for src in agents/reviewers/*.md; do
  name="$(basename "$src" .md)"
  put "$src" ".claude/agents/$name.md"
done

# Orphans: generated files whose source no longer exists.
while IFS= read -r existing; do
  found=0
  for e in "${EXPECTED[@]}"; do [ "$e" = "$existing" ] && { found=1; break; }; done
  if [ "$found" -eq 0 ]; then
    if [ "$CHECK" -eq 1 ]; then
      echo "drift: $existing has no source in agents/ — run scripts/sync-adapters.sh" >&2
      FAIL=1
    else
      rm -f "$existing"
    fi
  fi
done < <(find .claude/skills .claude/agents .agents/workflows -name '*.md' -type f 2>/dev/null)

if [ "$CHECK" -eq 0 ]; then
  find .claude/skills -type d -empty -delete 2>/dev/null || true
  echo "adapters in sync: .claude/skills/ .claude/agents/ .agents/workflows/"
fi
exit "$FAIL"
